Repository visualbis/react-querybuilder, pull requests merged in 2024-03, with the labels that each got.

#102 fix(Filter): Console error on click the select date in filter for date measure XPS-29150
  src/QueryBuilder.tsx
Labels: bug_fix, Review effort [1-5]: 2

#104 fix(Forecast): The selection is retaining after deleting the forecast measure IRENT-3652
  src/controls/ValueEditor.tsx
Labels: Review effort [1-5]: 1, bug_fix

#105 fix(lint): too many line issues
  src/Rule.tsx
Labels: enhancement, Review effort [1-5]: 2

#108 fix(Variables): In Flexi filter, the selected variable name is not displayed. XPS-29426
  src/controls/ValueEditor.tsx
Labels: bug_fix, Review effort [1-5]: 2

#109 feat(Drill Down) : Disabled Advanced filter for Performance Build XPS-27939
  src/QueryBuilder.tsx
  src/QueryGenerator.tsx
Labels: enhancement, Review effort [1-5]: 2

#110 feat(Drill down) : Minor change XPS-27939
  src/types.ts
Labels: enhancement
